# Generated by Django 5.0.6 on 2024-06-25 02:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arrendamiento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nise', models.CharField(max_length=50)),
                ('med_agua', models.CharField(max_length=50)),
                ('num_casa', models.CharField(max_length=50)),
                ('alquiler', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ubicacion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('cedula', models.IntegerField(primary_key=True, serialize=False)),
                ('correo', models.EmailField(max_length=254)),
                ('p_nombre', models.CharField(max_length=50)),
                ('s_nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('p_apellido', models.CharField(max_length=50)),
                ('s_apellido', models.CharField(blank=True, max_length=50, null=True)),
                ('f_nacimiento', models.DateField()),
                ('edad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Inquilino',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('deuda', models.IntegerField()),
                ('apodo', models.CharField(max_length=50, null=True)),
                ('p_nombre', models.CharField(max_length=50)),
                ('s_nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('p_apellido', models.CharField(max_length=50)),
                ('s_apellido', models.CharField(blank=True, max_length=50, null=True)),
                ('f_nacimiento', models.DateField()),
                ('edad', models.IntegerField()),
                ('id_casa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rentals.arrendamiento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentals.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50, null=True)),
                ('fecha', models.DateField()),
                ('luz', models.DecimalField(decimal_places=2, max_digits=10)),
                ('agua', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('restante', models.DecimalField(decimal_places=2, max_digits=10)),
                ('completado', models.BooleanField()),
                ('id_inquilino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentals.inquilino')),
            ],
        ),
        migrations.AddField(
            model_name='arrendamiento',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentals.tipo'),
        ),
        migrations.AddField(
            model_name='arrendamiento',
            name='ced_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentals.usuario'),
        ),
        migrations.CreateModel(
            name='Contribucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentals.pago')),
            ],
            options={
                'unique_together': {('id_pago', 'fecha')},
            },
        ),
        migrations.CreateModel(
            name='TelefonoInquilino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(max_length=20)),
                ('inquilino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentals.inquilino')),
            ],
            options={
                'unique_together': {('inquilino', 'telefono')},
            },
        ),
        migrations.CreateModel(
            name='TelefonoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(max_length=20)),
                ('cedula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentals.usuario')),
            ],
            options={
                'unique_together': {('cedula', 'telefono')},
            },
        ),
    ]
