# Generated by Django 5.0.6 on 2024-07-03 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0002_alter_usuario_options_alter_usuario_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arrendamiento',
            name='num_casa',
        ),
        migrations.AddField(
            model_name='arrendamiento',
            name='nombre',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
